[package]
name = "telegram-api-rs"
version = "0.1.0"
authors = ["jrmbchtl <s8jmbech@stud.uni-saarland.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
